#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# ===========================================
#               🔰 Pre Commit
# ============================================ */

# --- 🔸 Script checks ---

npx lint-staged
npm test